{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/component: kube-rbac-proxy
        app.kubernetes.io/created-by: promoter
        app.kubernetes.io/instance: controller-manager-metrics-service
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: service
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/part-of: promoter
        control-plane: controller-manager
    name: {{ include "promoter.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: {{ .Values.metrics.port }}
          protocol: TCP
          targetPort: https
    selector:
        control-plane: controller-manager
{{- end }}
