apiVersion: v1
kind: Service
metadata:
    name: {{ include "promoter.resourceName" (dict "suffix" "webhook-receiver" "context" $) }}
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - port: 3333
          protocol: TCP
          targetPort: 3333
    selector:
        control-plane: controller-manager
