apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        app.kubernetes.io/component: rbac
        app.kubernetes.io/created-by: promoter
        app.kubernetes.io/instance: leader-election-rolebinding
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: rolebinding
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/part-of: promoter
    name: {{ include "promoter.resourceName" (dict "suffix" "leader-election-rolebinding" "context" $) }}
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "promoter.resourceName" (dict "suffix" "leader-election-role" "context" $) }}
subjects:
    - kind: ServiceAccount
      name: {{ include "promoter.resourceName" (dict "suffix" "controller-manager" "context" $) }}
      namespace: {{ .Release.Namespace }}
