{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/component: kube-rbac-proxy
        app.kubernetes.io/created-by: promoter
        app.kubernetes.io/instance: metrics-reader
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: clusterrole
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/part-of: promoter
    name: {{ include "promoter.resourceName" (dict "suffix" "metrics-reader" "context" $) }}
rules:
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
{{- end }}
